In [1]:
#!pip install sympy

In [8]:
import sympy
import numpy as np

import Rotation_Matrix 
import Transformation_Matrix

In [9]:
print(Rotation_Matrix.rotation_matrix('z', 90))

[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]


In [10]:
print(Transformation_Matrix.transformation_matrix(0,0,0,0))

[[ 1. -0.  0.  0.]
 [ 0.  1. -0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
